### ISSUE TITLE
请问核心为何无法启动？

### ISSUE THREAD

**Issue by f59375543** [JiJiDown/jithon#6]
![20231104223754](https://github.com/JiJiDown/jithon/assets/43315911/c98ffe32-efdd-449b-94b3-7db590704dd8)

**Comment by o5-null** [comment]
现在jithon已经放弃维护。请转用2.0官方webui

**Comment by f59375543** [comment]
> webui

请问能指个路吗，谢谢

**Comment by o5-null** [comment]
http://client.jijidown.com/

**Comment by f59375543** [comment]
> http://client.jijidown.com/

谢谢
